name: shopping-api

services:
  mysql:
    image: mysql:8.1
    container_name: shopping-api-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p ${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
